"""Chapter-specific analytical questions for generated worked examples."""

from __future__ import annotations

# question, practical reason, principal validation check, extension data
LAB_CONTEXT: dict[int, tuple[str, str, str, str]] = {
    1: (
        "How is an unpaid contractual cash flow converted into present-value loss?",
        "Loss depends on amount, timing, recoveries, and workout costs; a default flag alone cannot measure it.",
        "Recalculate every discounted period and test the signs of recoveries and costs.",
        "the miniature cash-flow schedule and the synthetic retail portfolio",
    ),
    2: (
        "How do mean loss and tail loss differ?",
        "Expected loss supports central-tendency decisions, whereas solvency and concentration questions depend on the loss distribution.",
        "Verify that state probabilities sum to one and that their probability-weighted losses reproduce expected loss.",
        "the exact two-account case and the synthetic corporate portfolio",
    ),
    3: (
        "What changes when PD, LGD, and EAD deteriorate together?",
        "Multiplying separately averaged parameters ignores dependence and can understate downturn loss.",
        "Compare account-level scenario aggregation with the product of separately averaged components.",
        "the synthetic retail and synthetic IFRS 9 scenario datasets",
    ),
    4: (
        "How should credit events be represented through time?",
        "Cohort age, calendar conditions, censoring, and competing exits change the denominator of every rate.",
        "Reconcile the risk set and confirm that each transition row sums to one.",
        "the synthetic behavioural history and synthetic IFRS 9 schedule",
    ),
    5: (
        "Which statistical formulation matches the credit question?",
        "Classification, regression, survival, and multi-state models estimate different quantities and cannot be exchanged by changing an algorithm name.",
        "State the unit, event, horizon, censoring rule, and output domain for each formulation.",
        "the Taiwan credit-card data and a synthetic recovery dataset",
    ),
    6: (
        "How do data, estimation, policy, implementation, and monitoring form one model lifecycle?",
        "A sound estimator can still fail when definitions or transformations change between development and use.",
        "Change one versioned input and confirm that the run identifier and documented output change together.",
        "a synthetic retail run and a synthetic IFRS 9 close",
    ),
    7: (
        "Why do product contracts create different risk measures?",
        "Amortising loans, cards, and mortgages generate different exposure paths, prepayment behaviour, and relevant features.",
        "Reconcile balances, limits, and cash-flow timing under each product definition.",
        "synthetic retail products and the Taiwan credit-card data",
    ),
    8: (
        "How should obligor and facility risk be separated in SME and corporate lending?",
        "Financial strength belongs primarily to the obligor, while collateral, seniority, and utilisation belong to facilities.",
        "Check consolidation perimeter, statement date, currency, and ratio denominators.",
        "the synthetic corporate IRB and Polish bankruptcy datasets",
    ),
    9: (
        "Which risks are distinct in BNPL and embedded credit?",
        "Credit loss, affordability, fraud, merchant disputes, and repeat use have different outcomes and controls.",
        "Keep each target and its denominator separate and inspect repeat-borrowing exposure.",
        "the synthetic retail and synthetic fraud datasets",
    ),
    10: (
        "When does segmentation improve estimation rather than merely rename customers?",
        "Segments are useful only when risk relationships or operational treatment differ sufficiently and sample sizes remain credible.",
        "Compare event counts, calibration, and parameter stability within and across candidate segments.",
        "South German Credit and Polish bankruptcy data",
    ),
    11: (
        "What data are generated at each stage of a credit account?",
        "Application, servicing, delinquency, default, and recovery records have different observation units and time stamps.",
        "Test permitted state transitions and reconcile event-level balances to account-level outcomes.",
        "synthetic behavioural history and synthetic recovery cash flows",
    ),
    12: (
        "How are model estimates combined with affordability and credit policy?",
        "PD estimates expected risk; it does not encode delegated authority, affordability, or risk appetite.",
        "Hold PD constant while varying policy inputs and confirm that the reason codes identify the changed rule.",
        "the synthetic retail portfolio and BLS household expenditure microdata",
    ),
    13: (
        "How do the standardised and IRB approaches translate exposure into regulatory capital?",
        "The approaches use different inputs and permissions, so their outputs cannot be compared without the same regulatory perimeter.",
        "Reconcile exposure, risk weight, RWA, and the corresponding capital amount.",
        "the synthetic corporate IRB portfolio and EBA Pillar 3 aggregates",
    ),
    14: (
        "Why are default and IRB asset class determined before parameter estimation?",
        "Definitions determine the event population and the regulatory formula branch.",
        "Reclassify one exposure and show every downstream change in target, parameter, and capital output.",
        "the synthetic corporate portfolio and Basel worked classifications",
    ),
    15: (
        "What evidence shows that an internal rating system is used consistently?",
        "A rating system used only for reporting is not embedded in risk management and may not satisfy the intended use test.",
        "Compare assigned grades, observed outcomes, overrides, pricing, limits, and review actions by grade.",
        "the synthetic corporate portfolio and EBA disclosure aggregates",
    ),
    16: (
        "How does IFRS 9 change the loss horizon after significant credit deterioration?",
        "Stage assignment determines whether twelve-month or lifetime ECL is measured.",
        "Recalculate an account under Stage 1, Stage 2, and Stage 3 assumptions while retaining all stage reasons.",
        "the synthetic IFRS 9 schedule and official macroeconomic series",
    ),
    17: (
        "How does CECL differ from IFRS 9 despite a shared expected-loss objective?",
        "CECL generally recognises lifetime expected loss from initial recognition, whereas IFRS 9 changes horizon by stage.",
        "Keep the same contractual schedule and isolate the effect of horizon, staging, forecast, and reversion assumptions.",
        "a synthetic receivables schedule and a synthetic staged-loan schedule",
    ),
    18: (
        "How do consumer, discrimination, privacy, and AI rules affect model design?",
        "Predictive accuracy does not establish lawful use or sufficient reasons for an adverse action.",
        "Trace each model input and decision reason to purpose, legal review, and customer-facing explanation.",
        "HMDA decision data and a synthetic application portfolio",
    ),
    19: (
        "Which data source is suitable for a particular credit-risk estimand?",
        "Source usefulness depends on observation unit, timing, target meaning, population, and permitted use.",
        "Complete the suitability record before modelling and reject target substitutions such as approval for default.",
        "multiple UCI datasets and the project synthetic cases",
    ),
    20: (
        "What permissions and attribution are required before data are downloaded or redistributed?",
        "Public access describes availability, not necessarily the permitted use of raw or derived data.",
        "Verify publisher, current terms, attribution, redistribution, checksum, and access date.",
        "South German Credit and a conditional Kaggle source",
    ),
    21: (
        "How are application, facility, monthly performance, and bureau records joined as of a decision date?",
        "An unrestricted join can introduce future information or duplicate exposure.",
        "Verify join cardinality, source availability time, and account totals before and after the join.",
        "synthetic behavioural history and an independently generated mortgage panel",
    ),
    22: (
        "How are observation and performance windows constructed without leakage?",
        "Features must exist by the reference date and outcomes must mature after it.",
        "Test every feature timestamp and exclude observations whose outcome window is incomplete.",
        "synthetic behavioural history and the Taiwan credit-card payment history",
    ),
    23: (
        "How are data defects detected, explained, corrected, or excluded?",
        "Automatic imputation can hide source failure and alter model relationships.",
        "Retain the raw value, record the rule and disposition, and reconcile row counts and balances after cleaning.",
        "controlled defective copies of South German Credit and synthetic behavioural history",
    ),
    24: (
        "How are maxDPD, lastDPD, delinquency counts, utilisation, and recent-contract counts constructed?",
        "These features summarise different aspects of recency, severity, frequency, and exposure and therefore should not be treated as substitutes.",
        "Calculate each feature from raw event rows and prove that no event after the reference date enters the result.",
        "synthetic behavioural history and student-supplied longitudinal credit data",
    ),
    25: (
        "What should exploratory analysis establish before scorecard binning?",
        "Volumes, missingness, event rates, timing, and segment behaviour determine whether a characteristic is interpretable and stable.",
        "Reconcile counts and default rates from raw records to every displayed bin.",
        "synthetic retail data and South German Credit",
    ),
    26: (
        "How are expert-defined numeric and categorical bins implemented reproducibly?",
        "Manual bins can encode business structure, but boundary and missing-value rules must be explicit.",
        "Test every cut point, special value, missing value, and unseen category.",
        "synthetic retail data and South German Credit",
    ),
    27: (
        "How do automated binning methods balance fit, support, monotonicity, and stability?",
        "Maximising development IV can create small and unstable bins.",
        "Repeat bin fitting across time and bootstrap samples and compare cut stability.",
        "synthetic retail data and Taiwan credit-card data",
    ),
    28: (
        "How do WOE and IV summarise the relationship between a characteristic and default?",
        "WOE compares conditional distributions; IV aggregates their separation and is not a causal or universal selection criterion.",
        "Reconcile goods and bads, test the sign convention, and perform smoothing sensitivity for zero cells.",
        "South German Credit and the synthetic retail portfolio",
    ),
    29: (
        "How does penalised logistic regression estimate scorecard coefficients?",
        "The likelihood connects WOE inputs to probability, while the penalty controls unstable coefficients under sparse or correlated data.",
        "Track the objective, gradient, coefficient step, and probability bounds at every IRLS iteration.",
        "synthetic retail data and South German Credit",
    ),
    30: (
        "How are calibrated odds translated into an additive score and reason codes?",
        "Score scaling changes units rather than risk ordering; bin points must reconcile exactly to model log odds.",
        "Verify base odds, points-to-double-the-odds, rounding, grade boundaries, and top adverse contributions.",
        "the fitted synthetic scorecard and a fitted South German scorecard",
    ),
    31: (
        "Which sample design gives credible development and out-of-time evidence?",
        "Random cross-validation can mix periods and policies, whereas future use requires evidence from later observations with mature outcomes.",
        "Verify chronology, maturity, entity separation, and transformation fitting within the development partition.",
        "synthetic retail dates and a no-date UCI benchmark",
    ),
    32: (
        "What do discrimination metrics and decision costs measure?",
        "AUC, KS, lift, and confusion costs answer different ranking and action questions.",
        "Recompute each metric from ordered predictions and show sensitivity to the decision threshold.",
        "Taiwan credit-card data and South German Credit",
    ),
    33: (
        "How are probabilities calibrated and converted into stable rating grades?",
        "Ratings aggregate account probabilities for use in reporting and decisions, but grade design can hide poor within-grade calibration.",
        "Compare predicted and observed rates by grade, time, and migration direction.",
        "synthetic corporate data and Taiwan credit-card data",
    ),
    34: (
        "How do tree ensembles capture nonlinear credit relationships?",
        "Trees partition the feature space by impurity reduction; ensembles reduce variance or sequentially correct errors.",
        "Recalculate candidate split gain and compare out-of-time calibration as well as AUC.",
        "Taiwan credit-card data and Polish bankruptcy data",
    ),
    35: (
        "How should explanations and group outcomes be evaluated?",
        "Local attribution describes a model computation; it does not establish causality, fairness, or a lawful adverse-action reason.",
        "Test explanation stability, faithfulness, subgroup support, calibration, and decision outcomes separately.",
        "synthetic retail data and HMDA decision data",
    ),
    36: (
        "What can be learned when outcomes are observed only for accepted applicants?",
        "Acceptance creates selection bias because rejected applicants lack performance outcomes.",
        "State which conditional quantity is identified and report sensitivity to explicit reject assumptions.",
        "Credit Approval data and a synthetic accepted/rejected population",
    ),
    37: (
        "How is time to default estimated with censoring?",
        "Survival analysis uses the changing risk set rather than treating every censored account as a non-default.",
        "Reconstruct risk sets, event counts, and survival products at each event time.",
        "synthetic lifetime data and an independently generated mortgage-performance panel",
    ),
    38: (
        "How are conditional hazards converted into marginal and cumulative PD?",
        "Period ECL requires first-default probability in each period rather than repeated cumulative probability.",
        "Confirm that cumulative PD equals one minus the product of period survival probabilities.",
        "the synthetic IFRS 9 schedule and rating-transition simulations",
    ),
    39: (
        "How should PD be estimated when very few defaults are observed?",
        "Sparse events create wide uncertainty; zero observed defaults do not imply zero underlying PD.",
        "Report posterior sensitivity to prior choice and compare credible intervals with frequentist bounds.",
        "Polish bankruptcy data and a synthetic low-default portfolio",
    ),
    40: (
        "How is workout LGD reconstructed from post-default cash flows?",
        "Recovery amount, timing, workout costs, cure, and incomplete resolution all affect economic loss.",
        "Independently rebuild one account and reconcile discounted cash flows to account and portfolio totals.",
        "the synthetic recovery dataset and student-supplied lawful recovery data",
    ),
    41: (
        "Which model represents the mass points and continuous part of LGD?",
        "LGD often combines cure or full recovery with continuous severity and may require downturn calibration for regulatory use.",
        "Evaluate component probabilities, conditional severity, monetary bias, bounds, and segment calibration.",
        "synthetic recovery cash flows and corporate bankruptcy indicators",
    ),
    42: (
        "How are revolving exposure and CCF estimated?",
        "A borrower may draw available credit before default, so current balance alone can understate exposure.",
        "Separate zero-undrawn and line-change cases and validate both CCF and currency EAD.",
        "synthetic revolving facilities and student-supplied longitudinal card data",
    ),
    43: (
        "How are marginal PD, LGD, EAD, discounting, and scenarios combined in an ECL engine?",
        "Component definitions must share account, period, scenario, currency, and horizon before multiplication.",
        "Reconcile period, scenario, account, portfolio, and posted totals.",
        "the synthetic IFRS 9 schedule and official macroeconomic series",
    ),
    44: (
        "How is significant credit deterioration translated into stage assignment?",
        "Stage 2 depends on multiple quantitative and qualitative indicators, while Stage 3 follows credit-impaired/default criteria.",
        "Preserve all trigger reasons and test precedence, cure, probation, and backstop cases.",
        "the synthetic IFRS 9 schedule and a synthetic watchlist history",
    ),
    45: (
        "How do macroeconomic paths enter PD, LGD, EAD, and scenario weights?",
        "Forward-looking ECL requires internally coherent parameter paths rather than independent multipliers.",
        "Test coefficient signs, scenario ordering, weights, forecast vintage, and nonlinear weighting effects.",
        "World Bank, Eurostat, ECB, or FRED series and the synthetic ECL schedule",
    ),
    46: (
        "How do contractual timing, EIR discounting, and prepayment affect cash shortfalls?",
        "The same undiscounted shortfall has a different present value when its timing changes, and prepayment changes the exposure path.",
        "Reconcile contractual and expected cash flows period by period and test day-count conventions.",
        "the synthetic IFRS 9 schedule and a synthetic revolving schedule",
    ),
    47: (
        "When are provision matrices or CECL methods appropriate, and how are overlays separated?",
        "Method choice follows data and portfolio behaviour; management adjustments address specified gaps outside the base estimate.",
        "Reconcile historical rates, forward adjustments, model ECL, overlay, and final allowance.",
        "a synthetic trade-receivables matrix and a synthetic CECL loan schedule",
    ),
    48: (
        "How are stress effects and ECL movements reconciled and explained?",
        "A scenario result is credible only when scope, drivers, and accounting movements reconcile.",
        "Attribute changes to volume, stage, parameters, scenario, write-off, and overlay under a stated ordering.",
        "the synthetic IFRS 9 schedule and Federal Reserve stress paths",
    ),
    49: (
        "How is corporate or SME IRB capital calculated from PD, LGD, EAD, and maturity?",
        "The formula converts long-run parameters and systematic dependence into a stressed conditional loss measure.",
        "Reproduce correlation, stressed PD, maturity adjustment, capital rate, and RWA independently.",
        "the synthetic corporate IRB portfolio and Basel reference inputs",
    ),
    50: (
        "Why do mortgage, qualifying revolving retail, and other retail exposures use different IRB correlations?",
        "Different prescribed correlation functions change capital even when PD, LGD, and EAD are identical.",
        "Hold parameters constant and isolate the asset-class formula effect.",
        "synthetic retail exposures and Basel reference inputs",
    ),
    51: (
        "How are grade PDs aligned with long-run average default experience?",
        "Raw estimates can be cyclically or compositionally biased and require approved calibration and conservatism.",
        "Reconcile exposure-weighted calibrated PD to the stated target before adding MoC.",
        "synthetic corporate grades and EBA disclosure aggregates",
    ),
    52: (
        "How are downturn LGD, CCF, floors, and defaulted-asset treatments applied?",
        "Regulatory parameters have a different purpose from point-in-time accounting estimates.",
        "Show raw estimate, downturn adjustment, MoC, floor, and final parameter as separate columns.",
        "synthetic recovery and revolving datasets",
    ),
    53: (
        "How do systematic dependence and concentration affect portfolio tail loss?",
        "Expected loss may remain similar while a common factor or large exposure raises extreme outcomes.",
        "Compare mean, tail quantile, expected shortfall, HHI, and largest-obligor contribution.",
        "the synthetic corporate portfolio under granular and concentrated weights",
    ),
    54: (
        "How are counterparty exposure, netting, collateral, and CVA connected?",
        "Future exposure is market-dependent and legally valid netting determines which positive and negative values may offset.",
        "Reconcile trade, netting-set, collateral, expected-exposure, marginal-PD, and CVA totals.",
        "synthetic counterparty profiles and Basel SA-CCR reference cases",
    ),
    55: (
        "What constitutes independent and proportionate model validation?",
        "Validation evaluates conceptual soundness, data, performance, implementation, use, and governance rather than repeating development output.",
        "Trace every conclusion to independent evidence and record scope, severity, owner, and due date.",
        "a synthetic corporate model and a synthetic retail scorecard",
    ),
    56: (
        "How are assigned PDs backtested without reducing validation to one test?",
        "Calibration, discrimination, stability, and benchmark performance are distinct properties.",
        "Report sample size, defaults, uncertainty interval, test assumptions, and economic materiality by grade and time.",
        "synthetic corporate grades and Taiwan credit-card data",
    ),
    57: (
        "How are LGD, EAD, ECL, and stress models validated in their natural units?",
        "Percentage accuracy can hide monetary concentration and component errors can offset in aggregate ECL.",
        "Validate account- and exposure-weighted bias, tails, segments, and reconciliation separately.",
        "synthetic recovery, revolving, and IFRS 9 datasets",
    ),
    58: (
        "How does user acceptance testing establish implementation correctness?",
        "A statistically valid model can be implemented incorrectly at boundaries, rounding rules, or service transformations.",
        "Compare reference and production outputs at every intermediate step and retain signed exceptions.",
        "golden synthetic scorecard cases and synthetic IFRS 9 accounts",
    ),
    59: (
        "How are calibrated risk estimates translated into cutoff, price, and profitability decisions?",
        "The economically preferred threshold depends on margin, loss, cost, capital, take-up, and affordability—not AUC alone.",
        "Recalculate expected value under alternative cutoffs and stress each economic assumption.",
        "the synthetic retail portfolio and a CC BY credit dataset",
    ),
    60: (
        "How can sequential methods be studied without experimenting on real borrowers?",
        "Credit limits and collections create delayed, censored feedback and customer consequences.",
        "Use simulation or historical policy evaluation, enforce action constraints, and report off-policy uncertainty.",
        "the synthetic revolving and synthetic collections datasets",
    ),
    61: (
        "What information is needed to reproduce an approved model run?",
        "Coefficients alone omit data, code, configuration, environment, and policy versions.",
        "Reproduce the result from a clean environment and verify all recorded hashes.",
        "a synthetic retail scoring run and a synthetic IFRS 9 close",
    ),
    62: (
        "How should batch and real-time scoring preserve the approved calculation?",
        "Different service architectures must produce the same transformations, probability, score, grade, and reasons.",
        "Run golden cases through development and serving paths and compare every intermediate value.",
        "the synthetic retail scorecard and boundary-case requests",
    ),
    63: (
        "Which technical and governance conditions precede production deployment?",
        "Testing, security, approval, reconciliation, and rollback address different failure modes.",
        "Block deployment whenever a mandatory condition fails and test rollback with compatible schema and model versions.",
        "the complete repository test suite and synthetic production requests",
    ),
    64: (
        "Which monitoring evidence is available immediately and which requires mature outcomes?",
        "Input and score drift are leading indicators; calibration and default performance are observed only after the outcome horizon matures.",
        "Report data, prediction, decision, outcome, calibration, and group metrics with their own denominators and dates.",
        "synthetic time-shifted portfolios and mature outcome vintages",
    ),
    65: (
        "How are incidents contained and models recalibrated, redeveloped, rolled back, or retired?",
        "The appropriate response depends on customer, accounting, capital, security, and operational impact.",
        "Record detection, severity, containment, correction, customer impact, approval, and post-incident review.",
        "synthetic service incidents and synthetic calibration deterioration",
    ),
    66: (
        "How does the model inventory support ownership, change control, and audit?",
        "An inventory connects each model to purpose, data, version, validation, deployment, dependencies, findings, and retirement status.",
        "Follow one change from request through testing, approval, implementation, monitoring, and immutable history.",
        "a synthetic model inventory and hash-linked change records",
    ),
    67: (
        "Which NLP representation and metric fit a credit-document task?",
        "Classification, extraction, retrieval, and summarisation have different units and error costs.",
        "Compare tokenisation choices and report class- or field-specific performance.",
        "synthetic credit documents and CFPB complaint text obtained under the current notice",
    ),
    68: (
        "How are document fields and policy passages extracted while preserving source provenance?",
        "A claim is reviewable only when it links to the correct document, page, offsets, version, and access rights.",
        "Measure field accuracy, retrieval recall, citation support, and as-of-date validity.",
        "synthetic documents and SEC filings retrieved under fair-access rules",
    ),
    69: (
        "How can an LLM draft a credit memorandum without treating generated prose as evidence?",
        "Language-model probability is not truth, policy compliance, or PD.",
        "Validate structured fields, citations, missing evidence, unsupported claims, and permitted recommendation values.",
        "synthetic application packets and approved policy documents",
    ),
    70: (
        "How are an agent’s tools, memory, evidence, and authority restricted?",
        "The final answer is insufficient for safety assessment because tool calls and data access occur throughout the workflow.",
        "Evaluate every action against deterministic role, scope, evidence, approval, and time rules.",
        "synthetic documents and synthetic model-review records",
    ),
    71: (
        "How can document review be automated while retaining human credit authority?",
        "Automation can reduce clerical work, but missing or inconsistent evidence requires an authorised reviewer.",
        "Trace each extracted fact and proposed action to source spans, policy, and the recorded human decision.",
        "synthetic credit packets and synthetic policy documents",
    ),
    72: (
        "What evidence is required before releasing an LLM or agent workflow in credit risk?",
        "Evaluation must cover task performance, citations, permissions, security, robustness, subgroup effects, and incident response.",
        "Treat prohibited actions, secret exposure, unsupported critical claims, or approval bypass as release-blocking failures.",
        "all reviewed synthetic agent cases and a controlled red-team suite",
    ),
}


# One result-specific interpretation is printed after each executed code block. These
# statements describe only what the miniature example establishes; they deliberately
# avoid generalising the result to a lender population.
RESULT_INTERPRETATION: dict[int, str] = {
    1: "The present-value loss is EUR 390.26. Month 1 contributes zero because the contractual payment was received; months 2 and 3 contribute positive shortfalls after recoveries and costs.",
    2: "The zero-loss state is the most likely individual outcome, while low-probability default states create the upper tail. This is why the mean alone does not describe portfolio loss severity.",
    3: "The severe scenario has the smallest weight but the largest weighted contribution because PD, LGD and EAD deteriorate together. Separate averages would conceal that joint movement.",
    4: "Every displayed transition row sums to one. The absorbing prepaid state remains prepaid, while delinquent accounts can cure or worsen under the stated transition rules.",
    5: "The three outputs have different meanings: account default probability, conditional loss severity and cumulative time-to-default probability. Similar numeric ranges do not make them interchangeable targets.",
    6: "The run identifier contains 64 hexadecimal characters, as expected for SHA-256. It identifies the stated inputs; it does not prove that those inputs or the model are appropriate.",
    7: "The term loan has no undrawn component, whereas the card's 0.65 conversion factor raises EAD from EUR 2,000 drawn to EUR 5,900. Product terms determine the exposure calculation.",
    8: "The table computes obligor ratios from financial statements while retaining facility-level amounts separately. Changing a denominator changes the economic interpretation, not merely the displayed number.",
    9: "Each instalment consumes 6% of monthly income in the simplified schedule. Repeated use must be aggregated because an individually small payment can still create a material total burden.",
    10: "The rules assign borrowers to mutually exclusive segments from explicit thresholds. The labels are descriptive policy outputs; they are not evidence that the segments have different default behaviour.",
    11: "Each event follows an allowed predecessor in the miniature lifecycle. A valid state sequence is necessary before durations, migrations or cure rates can be estimated.",
    12: "The same calculation can return human-review eligibility or referral when affordability, PD appetite and delegated amount change. The reasons show which policy condition determined the result.",
    13: "RWA increases in direct proportion to the stated risk weight and exposure in this standardised illustration; minimum capital is 8% of RWA. Eligibility for a risk weight is a separate regulatory question.",
    14: "The output retains both the binary default flag and the criteria that triggered it. This prevents a downstream model target from losing the original default rationale.",
    15: "Observed rates exceed assigned PDs in the tiny grades, but each grade has only five observations. The example motivates uncertainty analysis rather than a conclusion of systematic miscalibration.",
    16: "The accounts enter Stages 1, 2 and 3 for distinct stated reasons. Stage assignment changes the measurement horizon; it is not a relabelling of the same ECL calculation.",
    17: "The calculated lifetime allowance is exposure multiplied by the historically based rate plus the stated qualitative adjustment. The adjustment is displayed separately so it can be challenged and removed.",
    18: "Approval and classification rates differ between the two small groups. These are descriptive sample differences; they do not establish discrimination or its cause without design, uncertainty and legal analysis.",
    19: "The suitability table assigns different sources to PD, fairness and macroeconomic questions. It demonstrates that dataset selection begins with the estimand rather than with file availability.",
    20: "The complete licence record passes, while the incomplete record fails for five named reasons. Access is blocked until source, permission, redistribution and attribution are resolved.",
    21: "Customer A receives the value effective before the decision date, not the later database value. Customer B remains missing because no eligible historical record exists.",
    22: "Only the default dated inside the stated 12-month performance window is labelled one. The later default is correctly excluded from that horizon.",
    23: "Only row 0 passes all rules; the defect table records why other rows are excluded. Row reconciliation makes the effect of cleaning measurable.",
    24: "The example distinguishes recency (`last_dpd`), severity (`max_dpd_6m`), frequency and new-credit activity. The values differ because each feature answers a different behavioural question.",
    25: "Default rates rise from 0% to 50% and 66.7% across the three illustrative utilisation bins. With only eight accounts, the pattern is a calculation check rather than stability evidence.",
    26: "Values exactly equal to 0.30 and 0.60 follow the declared closed-right boundaries, and missing values receive their own label. These cases determine production reproducibility.",
    27: "The largest adjacent p-value occurs for bins 2 and 3, so that pair is the next merge under the demonstrated ChiMerge rule. Other objectives can select different merges.",
    28: "Under the book's good-to-bad convention, the low-risk bin has positive WOE and the high-risk bin negative WOE. Their IV contributions dominate the nearly neutral middle bin.",
    29: "The first ridge-penalised IRLS step leaves the symmetric intercept at zero and moves the slope to 1.428571. Subsequent iterations, convergence and objective reduction still require testing.",
    30: "Doubling good-to-bad odds from 25:1 to 50:1 and again to 100:1 adds exactly 20 points each time, confirming the specified PDO scale.",
    31: "The partition table separates chronology and outcome maturity. Rows without a complete performance window cannot contribute to an out-of-time performance estimate.",
    32: "AUC 0.8889 and KS 0.6667 indicate strong ranking in the miniature sample, while the EUR 4,900 decision cost depends on the selected threshold and cost assumptions.",
    33: "The grade table compares mean assigned PD with observed default rate and population size. A zero observed rate in a three-account grade is not evidence of zero risk.",
    34: "Threshold 6 produces pure child nodes and the largest displayed Gini gain of 0.48. A single pure split can still overfit and must be tested on later data.",
    35: "The groups differ in approval and approved-account default rates in this fixture. Attribution to the model, policy or population requires separate counterfactual and legal analysis.",
    36: "The observed default rate of 0.333 applies only to accepted applicants. Two rejected applicants have no outcome, so population default risk is not identified from this table alone.",
    37: "Survival falls from 1.0 to 0.8 and then 0.6 as defaults occur in the changing risk set. Censored observations reduce later risk sets without being counted as non-defaults forever.",
    38: "Marginal PD equals surviving probability times current hazard. The cumulative curve grows without summing hazards directly, so first-default probability is not counted twice.",
    39: "Five defaults in 400 observations give a 1.25% raw rate; the stated prior moves the posterior mean to 2.0% and leaves a wide credible interval. Prior sensitivity is therefore material.",
    40: "Discounted net recoveries of EUR 2,149.73 against EUR 5,000 EAD produce workout LGD of 0.5701. Later recovery timing would reduce present value and increase LGD.",
    41: "The two-part calculation multiplies the probability of positive loss by conditional severity. The downturn multiplier raises each combined estimate while preserving the displayed component structure.",
    42: "Facilities with undrawn capacity have defined CCFs of 0.50 and 0.75. The fully drawn account has no valid CCF denominator, although its EAD remains measurable.",
    43: "The base scenario contributes EUR 65.282 and the downside EUR 84.090 after their weights, for total ECL of EUR 149.37. Weighting occurs after each scenario calculation.",
    44: "The four accounts show Stage 1, two distinct Stage 2 paths and Stage 3. Retaining all trigger flags reveals precedence when delinquency, watchlist and quantitative criteria overlap.",
    45: "The three scenario PDs are 2.46%, 3.626% and 8.394%; their probability-weighted value is 4.585%. The ordering reflects the stated macroeconomic coefficients, not an accounting judgement about weights.",
    46: "Later shortfalls receive smaller discount factors under the 12% annual effective rate. The month-3 EUR 1,000 shortfall has present value EUR 972.07, confirming the year-fraction convention.",
    47: "Each provision-matrix amount reconciles exposure, historical loss rate, forward factor and adjusted loss rate. The calculation makes the forward adjustment observable instead of embedding it in the history.",
    48: "The movement components produce a closing allowance of EUR 880,000, exactly equal to the posted balance in the fixture. Zero difference proves arithmetic reconciliation only.",
    49: "For the stated inputs, correlation is 0.164146 and the stressed conditional PD is 0.190259, producing a 9.1883% capital rate before any additional jurisdictional treatment.",
    50: "Identical PD, LGD and EAD produce different capital rates for mortgage and QRRE because the prescribed correlations differ. This numerical comparison does not establish asset-class eligibility.",
    51: "The calibrated grade PDs reproduce the 3.5% weighted target before named margins of conservatism are added. The final figures therefore retain both calibration and conservatism effects.",
    52: "The final LGD and CCF arrays show the effect of adjustment and floors on each raw parameter. A reviewer must reconcile each step rather than validate only the final value.",
    53: "Mean simulated loss is about 0.9%, whereas the 99.9th percentile is 6.12%. Dependence and finite-portfolio concentration affect tail loss far more than the mean.",
    54: "Period CVA contributions sum to EUR 5,683.20. The result is conditional on the supplied expected exposures, marginal PDs, recovery and independence approximation.",
    55: "The validation opinion is conditional because an independent benchmark remains open. Recording the finding prevents a qualified conclusion from being read as unconditional approval.",
    56: "None of the grade tests rejects its assigned PD in this small sample, but the large p-values also reflect limited power. Non-rejection is not proof of correct calibration.",
    57: "Account-weighted bias is 1.25 percentage points, exposure-weighted bias 1.33 points and the monetary error EUR 10,000. The measures differ because large accounts receive different weight.",
    58: "UAT fails because the score reconciliation is false even though PD, grade and reason checks pass. A material failed requirement cannot be averaged away.",
    59: "Expected profit rises across the three displayed cutoffs in this fixture and is highest at 0.12. The comparison is conditional on the margin, loss and applicant assumptions and ignores unobserved rejected outcomes.",
    60: "The middle action is selected most often and has the highest estimated reward in the simulation. The output explicitly remains a simulation and does not authorise a customer limit change.",
    61: "Canonical serialisation produces one repeatable run identifier from the recorded inputs. Changing field order outside the canonical representation would otherwise create an irrelevant hash difference.",
    62: "The valid request returns a versioned score response, while the missing debt-to-income field returns status 422. Explicit rejection prevents silent production imputation.",
    63: "Deployment is blocked solely because UAT reconciliation failed. This demonstrates that mandatory conditions are conjunctive rather than a weighted quality score.",
    64: "Input drift is measurable immediately, but 12-month calibration is unavailable because outcomes have not matured. Reporting it early would undercount defaults by construction.",
    65: "The severity mapping distinguishes service unavailability, a wrong model version and a late report. The wrong version receives the strongest response because continuing scores may be invalid.",
    66: "Versions 1.0 and 1.1 have different linked hashes. Verification detects a changed record, while ownership and approval still require independent access and identity controls.",
    67: "The tokenizer counts each displayed word and assigns `income` a TF-IDF score of 1.0 in the first document. The value depends on this corpus and tokenisation rule.",
    68: "BM25 ranks the verified-income passage first with a substantially higher score than the other passages. Retrieval relevance still requires an adjudicated support judgement.",
    69: "The memorandum passes schema and citation-identifier checks and recommends requesting evidence. Validation confirms contract compliance, not the truth of the cited content.",
    70: "Policy retrieval is read-only, human validation remains pending and customer approval is denied. The language component cannot convert evidence into decision authority.",
    71: "The assistant identifies a missing payslip, recommends requesting evidence and stops at pending human approval. The trace shows the ordered steps that produced that result.",
    72: "All three prohibited red-team actions are denied, so the displayed mandatory criteria pass for these cases. Release still depends on the complete evaluation set, not these three tests alone.",
}
